### ISSUE TITLE
Multiple tanker planned when several variants are available

### ISSUE THREAD

**Issue by Maveric33** [dcs-retribution/dcs-retribution#243]
### Is your feature request related to a problem? Please describe.

In a multi-aircraft campaign, we often have aircraft that need a KC-135 tanker and other KC-135 MPRSs, but why not S3-Bs too?

To date, when all 3 are available, Retribution only creates a single flight with 1 aircraft type.

### Describe the solution you'd like

Create a flight by tanker type
For all KC-135* models, a racetrack based on a base and at the distance defined in the threat distance doctrine.
So 2 flights, 1 in KC135 then a second in KC135 MPRS spaced a few nautical miles apart is all you need.
Then a 3rd in Hippodrome recovery mode on the CVN < Option integrated into DCS

### Additional context

DCS Liberation has implented this fonctionality from 6.0
https://github.com/dcs-liberation/dcs_liberation/blob/develop/changelog.md#600

In DCS
![image](https://github.com/dcs-retribution/dcs-retribution/assets/31960224/99ef17f8-39e8-4094-ae0d-8bc59d1e7d1c)

**Comment by Maveric33** [comment]
More information on how it works in Libération.

When you right-click on the CVN and select Refuel, it is automatically set to recovery, regardless of the type of tanker aircraft selected.

However, it is still recommended to have an S3B for this task.

**Comment by Maveric33** [comment]
Infos for systeme recovery tanker Liberation
https://github.com/dcs-liberation/dcs_liberation/pulls?q=is%3Apr+is%3Aclose+recovery

This will give you access to the code they made. I hope this will help you.

**Comment by Druss99** [comment]
Done, see: https://github.com/dcs-retribution/dcs-retribution/commit/dd7e4c908ef515983285c76edcba2c6a368eb7ca

**Comment by Raffson** [comment]
We're still missing a different type in the sense that if you have a KC-130 and a KC-135, you'd want to plan an additional tanker. I think this could be achieved relatively easy by looking at the number of tanker squadrons that have "unique" aircraft, if that makes sense? 😅

**Comment by Maveric33** [comment]
> We're still missing a different type in the sense that if you have a KC-130 and a KC-135, you'd want to plan an additional tanker. I think this could be achieved relatively easy by looking at the number of tanker squadrons that have "unique" aircraft, if that makes sense? 😅

Or more simply, it creates as many flight tankers as there are tanker squadrons.
For example, if there's 1 KC135 squadron and 1 MPRS squadron, create 2 flights with the same rules and a similar flight plan.

For me, S3-B tankers should be limited to recovery, as they have too little fuel to act as tankers.

**Comment by Maveric33** [comment]
> Done, see: [dd7e4c9](https://github.com/dcs-retribution/dcs-retribution/commit/dd7e4c908ef515983285c76edcba2c6a368eb7ca)

Thanks you for your integration

**Comment by Raffson** [comment]
> > Done, see: [dd7e4c9](https://github.com/dcs-retribution/dcs-retribution/commit/dd7e4c908ef515983285c76edcba2c6a368eb7ca)
> 
> 
> 
> Thanks you for your integration

That's only recovery tankers though, we'll get to the others in the next few weeks 🤞

**Comment by Druss99** [comment]
> We're still missing a different type in the sense that if you have a KC-130 and a KC-135, you'd want to plan an additional tanker. I think this could be achieved relatively easy by looking at the number of tanker squadrons that have "unique" aircraft, if that makes sense? 😅

Oh so we're currently only autoplanning one tanker, regardless of if it is a recovery tanker or not?

**Comment by Raffson** [comment]
> > We're still missing a different type in the sense that if you have a KC-130 and a KC-135, you'd want to plan an additional tanker. I think this could be achieved relatively easy by looking at the number of tanker squadrons that have "unique" aircraft, if that makes sense? 😅
> 
> Oh so we're currently only autoplanning one tanker, regardless of if it is a recovery tanker or not?

Multiple recovery tankers are planned, but theater tankers are only planned ("mission duration" / "tanker time on station") number of times, which is often just one tanker 😅
